### ISSUE TITLE
Display filters crash

### ISSUE THREAD

**Issue by islam2hamy** [phstudio2/Darktheme#8]
FATAL EXCEPTION: main
Process: com.phstudio.darktheme, PID: 3048
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/NotificationChannel;
	at com.phstudio.darktheme.Fragments.MyNotification.build(MyNotification.kt:27)
	at com.phstudio.darktheme.Fragments.OverlayService.onCreate(OverlayService.kt:34)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3249)
	at android.app.ActivityThread.-wrap5(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1615)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.NotificationChannel" on path: DexPathList[[zip file "/data/app/com.phstudio.darktheme-1/base.apk"],nativeLibraryDirectories=[/data/app/com.phstudio.darktheme-1/lib/arm64, /data/app/com.phstudio.darktheme-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 11 more

Os : miui 11.0.2
Android : 7.1.2

**Comment by pa238** [comment]
Fixed in [release 2.6](https://github.com/phstudio2/Darktheme/releases/tag/2.6)
